wazevo: passes simd f32/f64 cmp, rounding, pmax+pmin spec tests
tetratelabs/wazero pull request #1735
Opened 2023-09-25 18:18 UTC by evacchi

continues #1496

2023-09-25 20:57 UTC, mathetake requested changes

2023-09-25 20:57 UTC, mathetake commented on internal/integration_test/spectest/spectest.go
> +							panic("stop")
Garbage

2023-09-25 23:08 UTC, mathetake commented on internal/integration_test/spectest/spectest.go
> +						}
```suggestion
```

2023-09-25 23:08 UTC, mathetake approved these changes

2023-09-25 23:19 UTC, merged

2023-09-26 05:50 UTC, evacchi commented on internal/integration_test/spectest/spectest.go
> +							panic("stop")
Whoops!!