Fix path_symlink only works when dir mounted to /
tetratelabs/wazero pull request #2229
Opened 2024-06-05 05:42 UTC by yagehu

This commit fixes `path_symlink` not working when `-mount` is not supplied with a mapped directory.

fixes #2228

2024-06-05 14:04 UTC, mathetake requested changes
Please add the test case that ensures the behavior and previously failed.

2024-06-05 16:45 UTC, mathetake commented on imports/wasi_snapshot_preview1/fs_test.go
> +	success_cases := []struct {
In Go, we use CamelCase in general.

```suggestion
	successCases := []struct {
```

2024-06-05 16:48 UTC, mathetake commented on imports/wasi_snapshot_preview1/fs_test.go
> +	successCases := []struct {
this test case is named `Test_pathSymlink_errors`. Could you fix according to the change?

2024-06-05 16:51 UTC, mathetake approved these changes
looks good to me, waiting for others to review!

2024-06-06 02:39 UTC, anuraaga approved these changes
Thanks!

2024-06-06 02:51 UTC, merged